# Generated by Django 3.2.5 on 2021-07-04 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='default.png', upload_to='images/'),
            preserve_default=False,
        ),
    ]
